### ISSUE TITLE
unistd in main

### ISSUE THREAD

**Issue by ksundberg** [ksundberg/CS6300#46]
This header is not cross platform.  Its use needs to be replaced.

**Comment by ostlerc** [comment]
I made a comment on a closed pull request about this. I believe there is a chance the flex unistd.h file contains what we need. I will double check and make windows fixes if necessary.

**Comment by ostlerc** [comment]
I have a pull request that addresses this by using boost program options.

**Comment by ostlerc** [comment]
This issue can be closed.
